### ISSUE TITLE
Remove/destroy slides?

### ISSUE THREAD

**Issue by agarzola** [andygott/Really-Simple-Slideshow#2]
Hi! Thanks for sharing such a great plugin.

I’m using one slideshow stage to load selected slideshows upon request. That is, when the user clicks a certain link, I’d like to load a separate set of slides into the slideshow. Is there a way to add a method that is the opposite of `addSlides`? I don’t need to remove particular slides or anything, just get rid of all current slides. Something like `destroySlides` would work.

Is this easily achieved? I’ve been trying to work on it myself, but I’m a bit stuck. If you could point me in the right direction, I’d really appreciate it.

Thanks again!

**Comment by andygott** [comment]
Hi,

There isn't currently a method that exposes the internal slides array, but this is coming in the next release.

In the meantime, you could hack your way into the internal slides array, which is stored using the jQuery .data() method. Here's how you'd do this:

// Stop he slideshow, so that you don't get any errors
// when it attempts a transition and finds no data
$('#my-slideshow').rsfSlideshow('stopShow');
// Empty the slides array
$('#my-slideshow').data('rsf_slideshow').slides = [];
// Add your new slides
$('#my-slideshow').rsfSlideshow('addSlides', new_slides);
// Restart the slideshow
$('#my-slideshow').rsfSlideshow('startShow');

I hope this helps. The next release is only a few days away and will include a couple of new methods for this.

Andy.

**Comment by agarzola** [comment]
Thank you so much, Andy! I ended up just creating a public method that resets the data.slides array within the plugin, but nothing even remotely as elegant or robust as I’m sure you’ll be publishing in the days to come.

I’ll be using that new version as soon as it is published. Thanks again!
